services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "5000:5000"
    networks:
      - cortexnetwork
    # remove depends_on: envoy

  service-b-0-0-1:
    build: ./service-b-0-0-1
    container_name: service-b-0-0-1
    ports:
      - "5001:5001"
    networks:
      - cortexnetwork

  service-b-0-0-2:
    build: ./service-b-0-0-2
    container_name: service-b-0-0-2
    ports:
      - "5002:5002"
    networks:
      - cortexnetwork

  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
    networks:
      - cortexnetwork
    depends_on:
      - service-b-0-0-1
      - service-b-0-0-2

networks:
  cortexnetwork:
    driver: bridge
